### ISSUE TITLE
Gráfico de disco 

### ISSUE THREAD

**Issue by iurygregory** [analytics-ufcg/cloud-telemetry#16]
Ao selecionar um tempo maior que uma semana o gráfico não é mostrado, isso devido ao fato de que o json de retorno possui dados "antigos" que eram no formato {"total": 28835836, "percent": 82.3, "free": 3640908, "used": 23730148} enquanto os atuais são 
[{"device": "/", "percent": 48.1}, {"device": "/local", "percent": 0.1}]

**Comment by promulo** [comment]
Isso é simples de resolver. Basta apagar os dados da tabela no mysql...
