### ISSUE TITLE
Gráfico de uso de disco no Graphs/Hosts não aparece

### ISSUE THREAD

**Issue by Caio-Batista** [analytics-ufcg/cloud-telemetry#32]
O gráfico de Disk da aba Hosts não está aparecendo pra nenhum host em qualquer que seja o período de tempo.
Quando abro o console no caso de Last Hour está retornando um array vazio e pra qualquer outro tempo /javascript acusa a chamada de uma função não definida.

 Assim : 
Uncaught TypeError: undefined is not a function (index):1078
   (anonymous function) (index):1078
   jQuery.extend.each 0272dc9e5c21.js:35
   getPartitions (index):1076
   selectMetric (index):1032
   (anonymous function) (index):577
   fire 0272dc9e5c21.js:60
   self.fireWith 0272dc9e5c21.js:66
   done 0272dc9e5c21.js:478
   callback

**Comment by iurygregory** [comment]
Se isso for no horizon eu testei aqui ele só não plota o gráfico porém o retorno está correto.
